// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.OpenCommandLine
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenCommandLinePkgString = "f4ab1e64-5d35-4f06-bad9-bf414f4b3bbb";
        public static Guid guidOpenCommandLinePkg = new Guid(guidOpenCommandLinePkgString);

        public const string guidBatFileRuleString = "a549bda6-9370-43c1-821d-967560c031fc";
        public static Guid guidBatFileRule = new Guid(guidBatFileRuleString);

        public const string guidOpenCommandLineCmdSetString = "59c8a2ef-e017-4f2d-93ee-ca161749897d";
        public static Guid guidOpenCommandLineCmdSet = new Guid(guidOpenCommandLineCmdSetString);

        public const string guidImagesString = "bc10dceb-1833-4dac-bc42-286a81241664";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FlyoutMenu = 0x1000;
        public const int ContextMenuGroup = 0x1020;
        public const int CustomMenuGroup = 0x1030;
        public const int DefaultMenuGroup = 0x1040;
        public const int OptionsMenuGroup = 0x10450;
        public const int cmdidOpenCommandLine = 0x0100;
        public const int cmdidOpenCmd = 0x0200;
        public const int cmdidOpenPowershell = 0x0300;
        public const int cmdidOpenOptions = 0x0400;
        public const int cmdExecuteCmd = 0x0500;
        public const int WorkspaceFlyoutMenu = 0x2000;
        public const int WorkspaceMenuGroup = 0x2010;
        public const int WorkspaceCustomMenuGroup = 0x2020;
        public const int WorkspaceDefaultMenuGroup = 0x2030;
        public const int WorkspaceOptionsMenuGroup = 0x2040;
        public const int defaulted = 0x0001;
        public const int powershell = 0x0002;
        public const int cmd = 0x0003;
        public const int idmWSE_ContextMenu = 0x0002;
    }
}
