// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.OpenCommandLine
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidOpenCommandLinePkgString = "f4ab1e64-5d35-4f06-bad9-bf414f4b3bbb";
        public const string guidOpenCommandLineCmdSetString = "59c8a2ef-e017-4f2d-93ee-ca161749897d";
        public const string guidImagesString = "bc10dceb-1833-4dac-bc42-286a81241664";
        public static Guid guidOpenCommandLinePkg = new Guid(guidOpenCommandLinePkgString);
        public static Guid guidOpenCommandLineCmdSet = new Guid(guidOpenCommandLineCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FlyoutMenu = 0x1000;
        public const int ContextMenuGroup = 0x1020;
        public const int CustomMenuGroup = 0x1030;
        public const int DefaultMenuGroup = 0x1040;
        public const int OptionsMenuGroup = 0x10450;
        public const int cmdidOpenCommandLine = 0x0100;
        public const int cmdidOpenCmd = 0x0200;
        public const int cmdidOpenPowershell = 0x0300;
        public const int cmdidOpenOptions = 0x0400;
        public const int cmdExecuteCmd = 0x0500;
        public const int cmdidOpenCmdInOutput = 0x0600;
        public const int @default = 0x0001;
        public const int powershell = 0x0002;
        public const int cmd = 0x0003;
    }
}
