// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.OpenCommandLine
{
    static class Vsix
    {
        public const string Id = "f4ab1e64-5d35-4f06-bad9-bf414f4b3bbb";
        public const string Name = "Open Command Line";
        public const string Description = @"Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.";
        public const string Language = "en-US";
        public const string Version = "2.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "Solution Explorer, cmd, powershell, bash, post-git, cmder, prompt, console, conemu";
    }
}
