// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MadsKristensen.OpenCommandLine
{
    internal sealed partial class Vsix
    {
        public const string Id = "a7b534ac-949b-40f9-a795-deb511823941";
        public const string Name = "Open Command Line";
        public const string Description = @"Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.";
        public const string Language = "en-US";
        public const string Version = "2.6.999";
        public const string Author = "Mads Kristensen";
        public const string Tags = "Solution Explorer, cmd, powershell, execute";
        public const bool IsPreview = false;
    }
}
